### PR TITLE
Migrando todo sistema

### PR DESCRIPTION
**Pull request by Felipe-M-Duarte**
Conectado com MongoDB sem regras de controladores somente vamos fazer deploy e juntar front-end

### CODE REVIEW

**Comment by Felipe-M-Duarte** [comment]
good

**Review by Felipe-M-Duarte — COMMENTED** [review]
i aprrove

**Review by Backend-Felipemduarte — APPROVED** [review]
All good

**Review by Backend-Felipemduarte — APPROVED** [review]
all right

**Comment by seekayel** [comment]
This repository is a simple starter for Cyclic. This looks like you added a full ToDo app. That is great, but not the intent of this starter.

Do you think your repository would be a good addition to our tutorials?

**Pull request closed without merging**
